<?php


if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Trx_user_model extends CI_Model
{

    public $table = 'trx_user';
    public $id = 'u_id';
    public $order = 'DESC';
    public $tables = 'view_user';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    function total_rows($q = NULL, $xusername, $id_group) {

        if(!empty($xusername)){
            if($id_group=='5'){
                $this->db->group_start();
                $this->db->where('user_supervisor',$xusername);
                $this->db->where('id_group','2');
                $this->db->group_end(); 
                    } 
        } 
            $this->db->group_start();
            $this->db->like('username', $q);
        	$this->db->or_like('id_group', $q);
        	$this->db->or_like('user_password', $q);
        	$this->db->or_like('user_fullname', $q);
        	$this->db->or_like('user_email', $q);
        	$this->db->or_like('user_telp', $q);
        	$this->db->or_like('user_address', $q);
        	$this->db->or_like('user_status', $q);
        	$this->db->or_like('user_photo', $q);
        	$this->db->or_like('info1', $q);
        	$this->db->or_like('info2', $q);
        	$this->db->or_like('info3', $q);
        	$this->db->or_like('info4', $q);
        $this->db->group_end();
        	$this->db->from($this->tables);
        return $this->db->count_all_results();
    }



    public function tampil_data($limit, $start = 0, $q = NULL, $xusername, $id_group){
     
        if(!empty($xusername)){
            if($id_group=='5'){
                $this->db->group_start();
                $this->db->where('user_supervisor',$xusername);
                $this->db->where('id_group','2');
                $this->db->group_end(); 
                    }              
        }        
       
        $this->db->group_start();
        $this->db->like('username', $q);
            $this->db->or_like('id_group', $q);
            $this->db->or_like('user_password', $q);
            $this->db->or_like('user_fullname', $q);
            $this->db->or_like('user_email', $q);
            $this->db->or_like('user_telp', $q);
            $this->db->or_like('user_address', $q);
            $this->db->or_like('user_status', $q);
            $this->db->or_like('user_photo', $q);
            $this->db->or_like('info1', $q);
            $this->db->or_like('info2', $q);
            $this->db->or_like('info3', $q);
            $this->db->or_like('info4', $q);
        $this->db->group_end();

        $this->db->order_by('id_group', 'DESC');
        $this->db->limit($limit, $start);
        return $this->db->get($this->tables)->result();
    }


    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('username', $q);
	$this->db->or_like('id_group', $q);
	$this->db->or_like('user_password', $q);
	$this->db->or_like('user_fullname', $q);
	$this->db->or_like('user_email', $q);
	$this->db->or_like('user_telp', $q);
	$this->db->or_like('user_address', $q);
	$this->db->or_like('user_status', $q);
	$this->db->or_like('user_photo', $q);
	$this->db->or_like('info1', $q);
	$this->db->or_like('info2', $q);
	$this->db->or_like('info3', $q);
	$this->db->or_like('info4', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    public function randomPassword() {
        $chars = 'abcdefghijklmnopqrstuwxyzABCDEFGHIJKLMNOPQRSTUWXYZ0123456789';
        for($i = 0; $i < 8; ++$i) {
            $random = str_shuffle($chars);
            $ret .= $random[0];
        }
        return $ret ;

       
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Trx_user_model.php */
/* Location: ./application/models/Trx_user_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-04 14:45:35 */
/* http://harviacode.com */
