<?php


if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Trx_masterdetail_model extends CI_Model
{

    public $table = 'trx_masterdetail';
    public $id = 'masterdetail_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('masterdetail_id', $q);
	$this->db->or_like('masterdetail_master_id', $q);
	$this->db->or_like('masterdetail_karyawan_id', $q);
	$this->db->or_like('masterdetail_mulai', $q);
	$this->db->or_like('masterdetail_selesai', $q);
	$this->db->or_like('masterdetail_jamkerja', $q);
	$this->db->or_like('masterdetail_istirahat', $q);
	$this->db->or_like('masterdetail_totalkerja', $q);
	$this->db->or_like('masterdetail_box', $q);
	$this->db->or_like('masterdetail_jumlahstiker', $q);
	$this->db->or_like('masterdetail_jumlahkrat', $q);
	$this->db->or_like('masterdetail_upah', $q);
	$this->db->or_like('masterdetail_userinput', $q);
	$this->db->or_like('masterdetail_tglinput', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('masterdetail_id', $q);
	$this->db->or_like('masterdetail_master_id', $q);
	$this->db->or_like('masterdetail_karyawan_id', $q);
	$this->db->or_like('masterdetail_mulai', $q);
	$this->db->or_like('masterdetail_selesai', $q);
	$this->db->or_like('masterdetail_jamkerja', $q);
	$this->db->or_like('masterdetail_istirahat', $q);
	$this->db->or_like('masterdetail_totalkerja', $q);
	$this->db->or_like('masterdetail_box', $q);
	$this->db->or_like('masterdetail_jumlahstiker', $q);
	$this->db->or_like('masterdetail_jumlahkrat', $q);
	$this->db->or_like('masterdetail_upah', $q);
	$this->db->or_like('masterdetail_userinput', $q);
	$this->db->or_like('masterdetail_tglinput', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Trx_masterdetail_model.php */
/* Location: ./application/models/Trx_masterdetail_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-04 14:45:35 */
/* http://harviacode.com */
